pipeline:
  name: Sonarqube Test
  identifier: Sonarqube_Test
  projectIdentifier: SonarQube_Test_Project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Mission10_Connector
        build: <+input>
  stages:
    - stage:
        name: Scan python-flask stage
        identifier: Scan_pythonflask_stage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Manual sonar scan
                  identifier: Manual_sonar_scan
                  spec:
                    shell: Sh
                    command: |-
                      sonar-scanner \
                        -Dsonar.projectKey=python-flask-project \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=http://35.206.188.23:9000 \
                        -Dsonar.login=sqp_4701ae911823832500337f7290f45f173d610946
